'use client'
import { useState } from 'react'

export function CampaignActions({campaignId,status,scheduledAt}:{campaignId:string;status:string;scheduledAt?:string|null}){
  const [busy,setBusy]=useState(false);const [message,setMessage]=useState('')
  async function test(){const email=window.prompt('Send the test to which email?');if(!email)return;setBusy(true);setMessage('Sending test…');try{const res=await fetch('/api/test-send',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({campaignId,email})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Test failed');setMessage('Test sent.');setTimeout(()=>location.reload(),700)}catch(err){setMessage(err instanceof Error?err.message:'Test failed')}finally{setBusy(false)}}
  async function send(){if(status!=='tested'&&status!=='ready'){setMessage('Send a test first.');return}const isScheduled=Boolean(scheduledAt&&new Date(scheduledAt).getTime()>Date.now());const phrase=window.prompt(`${isScheduled?'This schedules':'This sends'} the campaign for every eligible EC contact in the Resend marketing segment. Type SEND to continue.`);if(phrase!=='SEND')return;if(!window.confirm(`Final confirmation: ${isScheduled?'schedule':'send'} this marketing campaign${isScheduled?` for ${new Date(scheduledAt!).toLocaleString()}`:' now'}?`))return;setBusy(true);setMessage(isScheduled?'Preparing audience and scheduling Broadcast…':'Preparing audience and submitting Broadcast…');try{const res=await fetch('/api/campaigns/send',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({campaignId,confirmation:'SEND'})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Send failed');setMessage(data.scheduledAt?`Broadcast scheduled for ${new Date(data.scheduledAt).toLocaleString()}. ${data.targeted} Supabase contacts were eligible.`:`Broadcast submitted. ${data.targeted} Supabase contacts were eligible.`);setTimeout(()=>location.reload(),1000)}catch(err){setMessage(err instanceof Error?err.message:'Send failed')}finally{setBusy(false)}}
  async function cancel(){if(status!=='scheduled')return;if(!window.confirm('Cancel this scheduled Broadcast? It will not be sent at the scheduled time.'))return;setBusy(true);setMessage('Cancelling schedule…');try{const res=await fetch('/api/campaigns/cancel',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({campaignId})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Cancellation failed');setMessage('Schedule cancelled. Campaign returned to tested.');setTimeout(()=>location.reload(),700)}catch(err){setMessage(err instanceof Error?err.message:'Cancellation failed')}finally{setBusy(false)}}
  const futureSchedule=Boolean(scheduledAt&&new Date(scheduledAt).getTime()>Date.now())
  return <div className="toolbar"><button className="secondary" onClick={test} disabled={busy||['preparing','scheduled','sending','sent'].includes(status)}>Send test</button>{status==='scheduled'?<button className="ghost" onClick={cancel} disabled={busy}>Cancel schedule</button>:<button onClick={send} disabled={busy||!['tested','ready'].includes(status)}>{futureSchedule?'Schedule audience':'Send audience'}</button>}{message&&<small>{message}</small>}</div>
}
