create extension if not exists pgcrypto;
create table if not exists public.ecm_contacts(id uuid primary key default gen_random_uuid(),email text not null unique,first_name text,last_name text,company text,phone text,address text,city text,state text,zip text,country text,notes text,source text not null default 'pixieset',source_type text,marketing_status text not null default 'eligible' check(marketing_status in('eligible','unsubscribed','bounced','complained','suppressed')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.ecm_imports(id uuid primary key default gen_random_uuid(),filename text not null,total_rows integer not null default 0,inserted_rows integer not null default 0,updated_rows integer not null default 0,skipped_rows integer not null default 0,created_at timestamptz not null default now());
create table if not exists public.ecm_campaigns(id uuid primary key default gen_random_uuid(),name text not null,subject text not null,preview_text text,body_html text not null default '',body_text text not null default '',cta_label text,cta_url text,status text not null default 'draft' check(status in('draft','tested','ready','sending','sent','failed')),send_token uuid,sent_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.ecm_campaign_recipients(id uuid primary key default gen_random_uuid(),campaign_id uuid not null references public.ecm_campaigns(id) on delete cascade,contact_id uuid not null references public.ecm_contacts(id) on delete cascade,resend_email_id text,status text not null default 'pending',last_event_at timestamptz,created_at timestamptz not null default now(),unique(campaign_id,contact_id));
create table if not exists public.ecm_email_events(id uuid primary key default gen_random_uuid(),resend_email_id text,event_type text not null,contact_email text,payload jsonb not null,received_at timestamptz not null default now());
create index if not exists ecm_contacts_marketing_status_idx on public.ecm_contacts(marketing_status);create index if not exists ecm_contacts_source_type_idx on public.ecm_contacts(source_type);create index if not exists ecm_campaign_recipients_resend_id_idx on public.ecm_campaign_recipients(resend_email_id);create index if not exists ecm_email_events_resend_id_idx on public.ecm_email_events(resend_email_id);
alter table public.ecm_contacts enable row level security;alter table public.ecm_imports enable row level security;alter table public.ecm_campaigns enable row level security;alter table public.ecm_campaign_recipients enable row level security;alter table public.ecm_email_events enable row level security;
revoke all on public.ecm_contacts from anon,authenticated;revoke all on public.ecm_imports from anon,authenticated;revoke all on public.ecm_campaigns from anon,authenticated;revoke all on public.ecm_campaign_recipients from anon,authenticated;revoke all on public.ecm_email_events from anon,authenticated;
